/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SaveProductVariantInput = IDL.Record({
  'active' : IDL.Bool,
  'retailPrice' : IDL.Int,
  'baseUnitId' : IDL.Nat,
  'cost' : IDL.Int,
  'name' : IDL.Text,
  'wholesalePrice' : IDL.Opt(IDL.Int),
  'productId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StockAdjustment = IDL.Record({
  'productId' : IDL.Nat,
  'variantId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'change' : IDL.Int,
  'reason' : IDL.Text,
});
export const PaymentBreakdown = IDL.Record({
  'methodId' : IDL.Nat,
  'amount' : IDL.Int,
});
export const TransactionStatus = IDL.Variant({
  'fullyRefunded' : IDL.Null,
  'partiallyRefunded' : IDL.Record({
    'originalAmount' : IDL.Int,
    'refundedAmount' : IDL.Int,
  }),
  'completed' : IDL.Null,
  'voided' : IDL.Record({ 'voidedBy' : IDL.Principal, 'timestamp' : IDL.Int }),
});
export const ProductUnit = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'conversionToBase' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : TransactionStatus,
  'refundedAmount' : IDL.Int,
  'payments' : IDL.Vec(PaymentBreakdown),
  'createdBy' : IDL.Principal,
  'totalAmount' : IDL.Int,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(
    IDL.Record({
      'unit' : ProductUnit,
      'productId' : IDL.Nat,
      'variantId' : IDL.Nat,
      'quantity' : IDL.Int,
      'price' : IDL.Int,
    })
  ),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const ProductCategory = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
});
export const PromotionEligibility = IDL.Record({
  'validFrom' : IDL.Opt(IDL.Int),
  'validTo' : IDL.Opt(IDL.Int),
  'minPurchaseAmount' : IDL.Opt(IDL.Int),
  'minQuantity' : IDL.Opt(IDL.Int),
});
export const PromotionType = IDL.Variant({
  'percentageDiscount' : IDL.Record({ 'percentage' : IDL.Float64 }),
  'buyOneGetOne' : IDL.Record({
    'discountVariantId' : IDL.Nat,
    'productId' : IDL.Nat,
    'discountQuantity' : IDL.Int,
    'variantId' : IDL.Nat,
    'discountProductId' : IDL.Nat,
  }),
  'fixedDiscount' : IDL.Record({ 'amount' : IDL.Int }),
});
export const Promotion = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Opt(IDL.Int),
  'createdBy' : IDL.Opt(IDL.Principal),
  'description' : IDL.Opt(IDL.Text),
  'eligibility' : PromotionEligibility,
  'promoType' : PromotionType,
  'updatedAt' : IDL.Opt(IDL.Int),
  'updatedBy' : IDL.Opt(IDL.Principal),
  'productTarget' : IDL.Opt(
    IDL.Record({ 'productId' : IDL.Nat, 'variantId' : IDL.Opt(IDL.Nat) })
  ),
  'promoId' : IDL.Nat,
});
export const PaymentMethodType = IDL.Variant({
  'creditCard' : IDL.Null,
  'custom' : IDL.Text,
  'cash' : IDL.Null,
  'bankTransfer' : IDL.Null,
  'debitCard' : IDL.Null,
  'qrCode' : IDL.Null,
});
export const PaymentMethod = IDL.Record({
  'id' : IDL.Nat,
  'methodType' : PaymentMethodType,
  'name' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const ProductVariant = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'active' : IDL.Bool,
  'retailPrice' : IDL.Int,
  'baseUnitId' : IDL.Nat,
  'cost' : IDL.Int,
  'name' : IDL.Text,
  'wholesalePrice' : IDL.Opt(IDL.Int),
});
export const SavePaymentMethodInput = IDL.Record({
  'methodType' : PaymentMethodType,
  'name' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const SaveProductInput = IDL.Record({
  'categoryId' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'variants' : IDL.Vec(ProductVariant),
});
export const SaveProductCategoryInput = IDL.Record({
  'active' : IDL.Bool,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProductVariant' : IDL.Func([SaveProductVariantInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInventoryAdjustment' : IDL.Func([StockAdjustment], [], []),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentBreakdown)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryList' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(ProductCategory)],
      ['query'],
    ),
  'getComboDeals' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
  'getPaymentMethodsByType' : IDL.Func(
      [PaymentMethodType],
      [IDL.Vec(PaymentMethod)],
      ['query'],
    ),
  'getProductVariantsByProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductVariant)],
      ['query'],
    ),
  'getTransactionsByPaymentMethod' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processRefund' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePaymentMethod' : IDL.Func([SavePaymentMethodInput], [IDL.Nat], []),
  'saveProduct' : IDL.Func([SaveProductInput], [IDL.Nat], []),
  'saveProductCategory' : IDL.Func([SaveProductCategoryInput], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SaveProductVariantInput = IDL.Record({
    'active' : IDL.Bool,
    'retailPrice' : IDL.Int,
    'baseUnitId' : IDL.Nat,
    'cost' : IDL.Int,
    'name' : IDL.Text,
    'wholesalePrice' : IDL.Opt(IDL.Int),
    'productId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StockAdjustment = IDL.Record({
    'productId' : IDL.Nat,
    'variantId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'change' : IDL.Int,
    'reason' : IDL.Text,
  });
  const PaymentBreakdown = IDL.Record({
    'methodId' : IDL.Nat,
    'amount' : IDL.Int,
  });
  const TransactionStatus = IDL.Variant({
    'fullyRefunded' : IDL.Null,
    'partiallyRefunded' : IDL.Record({
      'originalAmount' : IDL.Int,
      'refundedAmount' : IDL.Int,
    }),
    'completed' : IDL.Null,
    'voided' : IDL.Record({
      'voidedBy' : IDL.Principal,
      'timestamp' : IDL.Int,
    }),
  });
  const ProductUnit = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'conversionToBase' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : TransactionStatus,
    'refundedAmount' : IDL.Int,
    'payments' : IDL.Vec(PaymentBreakdown),
    'createdBy' : IDL.Principal,
    'totalAmount' : IDL.Int,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(
      IDL.Record({
        'unit' : ProductUnit,
        'productId' : IDL.Nat,
        'variantId' : IDL.Nat,
        'quantity' : IDL.Int,
        'price' : IDL.Int,
      })
    ),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ProductCategory = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
  });
  const PromotionEligibility = IDL.Record({
    'validFrom' : IDL.Opt(IDL.Int),
    'validTo' : IDL.Opt(IDL.Int),
    'minPurchaseAmount' : IDL.Opt(IDL.Int),
    'minQuantity' : IDL.Opt(IDL.Int),
  });
  const PromotionType = IDL.Variant({
    'percentageDiscount' : IDL.Record({ 'percentage' : IDL.Float64 }),
    'buyOneGetOne' : IDL.Record({
      'discountVariantId' : IDL.Nat,
      'productId' : IDL.Nat,
      'discountQuantity' : IDL.Int,
      'variantId' : IDL.Nat,
      'discountProductId' : IDL.Nat,
    }),
    'fixedDiscount' : IDL.Record({ 'amount' : IDL.Int }),
  });
  const Promotion = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Opt(IDL.Int),
    'createdBy' : IDL.Opt(IDL.Principal),
    'description' : IDL.Opt(IDL.Text),
    'eligibility' : PromotionEligibility,
    'promoType' : PromotionType,
    'updatedAt' : IDL.Opt(IDL.Int),
    'updatedBy' : IDL.Opt(IDL.Principal),
    'productTarget' : IDL.Opt(
      IDL.Record({ 'productId' : IDL.Nat, 'variantId' : IDL.Opt(IDL.Nat) })
    ),
    'promoId' : IDL.Nat,
  });
  const PaymentMethodType = IDL.Variant({
    'creditCard' : IDL.Null,
    'custom' : IDL.Text,
    'cash' : IDL.Null,
    'bankTransfer' : IDL.Null,
    'debitCard' : IDL.Null,
    'qrCode' : IDL.Null,
  });
  const PaymentMethod = IDL.Record({
    'id' : IDL.Nat,
    'methodType' : PaymentMethodType,
    'name' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const ProductVariant = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'active' : IDL.Bool,
    'retailPrice' : IDL.Int,
    'baseUnitId' : IDL.Nat,
    'cost' : IDL.Int,
    'name' : IDL.Text,
    'wholesalePrice' : IDL.Opt(IDL.Int),
  });
  const SavePaymentMethodInput = IDL.Record({
    'methodType' : PaymentMethodType,
    'name' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const SaveProductInput = IDL.Record({
    'categoryId' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'variants' : IDL.Vec(ProductVariant),
  });
  const SaveProductCategoryInput = IDL.Record({
    'active' : IDL.Bool,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProductVariant' : IDL.Func([SaveProductVariantInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInventoryAdjustment' : IDL.Func([StockAdjustment], [], []),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentBreakdown)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryList' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(ProductCategory)],
        ['query'],
      ),
    'getComboDeals' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
    'getPaymentMethodsByType' : IDL.Func(
        [PaymentMethodType],
        [IDL.Vec(PaymentMethod)],
        ['query'],
      ),
    'getProductVariantsByProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductVariant)],
        ['query'],
      ),
    'getTransactionsByPaymentMethod' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processRefund' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePaymentMethod' : IDL.Func([SavePaymentMethodInput], [IDL.Nat], []),
    'saveProduct' : IDL.Func([SaveProductInput], [IDL.Nat], []),
    'saveProductCategory' : IDL.Func([SaveProductCategoryInput], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };