/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PaymentBreakdown { 'methodId' : bigint, 'amount' : bigint }
export interface PaymentMethod {
  'id' : bigint,
  'methodType' : PaymentMethodType,
  'name' : string,
  'enabled' : boolean,
}
export type PaymentMethodType = { 'creditCard' : null } |
  { 'custom' : string } |
  { 'cash' : null } |
  { 'bankTransfer' : null } |
  { 'debitCard' : null } |
  { 'qrCode' : null };
export interface ProductCategory {
  'id' : bigint,
  'active' : boolean,
  'name' : string,
}
export interface ProductUnit {
  'id' : bigint,
  'name' : string,
  'conversionToBase' : number,
}
export interface ProductVariant {
  'id' : bigint,
  'sku' : string,
  'active' : boolean,
  'retailPrice' : bigint,
  'baseUnitId' : bigint,
  'cost' : bigint,
  'name' : string,
  'wholesalePrice' : [] | [bigint],
}
export interface Promotion {
  'couponCode' : [] | [string],
  'active' : boolean,
  'name' : string,
  'createdAt' : [] | [bigint],
  'createdBy' : [] | [Principal],
  'description' : [] | [string],
  'eligibility' : PromotionEligibility,
  'promoType' : PromotionType,
  'updatedAt' : [] | [bigint],
  'updatedBy' : [] | [Principal],
  'productTarget' : [] | [
    { 'productId' : bigint, 'variantId' : [] | [bigint] }
  ],
  'promoId' : bigint,
}
export interface PromotionEligibility {
  'validFrom' : [] | [bigint],
  'validTo' : [] | [bigint],
  'minPurchaseAmount' : [] | [bigint],
  'minQuantity' : [] | [bigint],
}
export type PromotionType = {
    'percentageDiscount' : { 'percentage' : number }
  } |
  {
    'buyOneGetOne' : {
      'discountVariantId' : bigint,
      'productId' : bigint,
      'discountQuantity' : bigint,
      'variantId' : bigint,
      'discountProductId' : bigint,
    }
  } |
  { 'fixedDiscount' : { 'amount' : bigint } };
export interface SavePaymentMethodInput {
  'methodType' : PaymentMethodType,
  'name' : string,
  'enabled' : boolean,
}
export interface SaveProductCategoryInput {
  'active' : boolean,
  'name' : string,
}
export interface SaveProductInput {
  'categoryId' : bigint,
  'active' : boolean,
  'name' : string,
  'variants' : Array<ProductVariant>,
}
export interface SaveProductVariantInput {
  'active' : boolean,
  'retailPrice' : bigint,
  'baseUnitId' : bigint,
  'cost' : bigint,
  'name' : string,
  'wholesalePrice' : [] | [bigint],
  'productId' : bigint,
}
export interface StockAdjustment {
  'productId' : bigint,
  'variantId' : bigint,
  'timestamp' : bigint,
  'change' : bigint,
  'reason' : string,
}
export interface Transaction {
  'id' : bigint,
  'status' : TransactionStatus,
  'refundedAmount' : bigint,
  'payments' : Array<PaymentBreakdown>,
  'createdBy' : Principal,
  'totalAmount' : bigint,
  'timestamp' : bigint,
  'items' : Array<
    {
      'unit' : ProductUnit,
      'productId' : bigint,
      'variantId' : bigint,
      'quantity' : bigint,
      'price' : bigint,
    }
  >,
}
export type TransactionStatus = { 'fullyRefunded' : null } |
  {
    'partiallyRefunded' : {
      'originalAmount' : bigint,
      'refundedAmount' : bigint,
    }
  } |
  { 'completed' : null } |
  { 'voided' : { 'voidedBy' : Principal, 'timestamp' : bigint } };
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProductVariant' : ActorMethod<[SaveProductVariantInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInventoryAdjustment' : ActorMethod<[StockAdjustment], undefined>,
  'getAllPayments' : ActorMethod<[], Array<PaymentBreakdown>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryList' : ActorMethod<[[] | [string]], Array<ProductCategory>>,
  'getComboDeals' : ActorMethod<[], Array<Promotion>>,
  'getPaymentMethodsByType' : ActorMethod<
    [PaymentMethodType],
    Array<PaymentMethod>
  >,
  'getProductVariantsByProduct' : ActorMethod<[bigint], Array<ProductVariant>>,
  'getTransactionsByPaymentMethod' : ActorMethod<[bigint], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processRefund' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePaymentMethod' : ActorMethod<[SavePaymentMethodInput], bigint>,
  'saveProduct' : ActorMethod<[SaveProductInput], bigint>,
  'saveProductCategory' : ActorMethod<[SaveProductCategoryInput], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];